Repository MOV-AI/backend, pull requests merged in 2023-07, with the labels that each got.

#136 pump dal version
  README.md
  setup.py
Labels: bug

#128 BP-984 + 985 stream logs to frontend
  .pylintrc
  backend/core/log_streamer/__init__.py
  backend/core/log_streamer/log_client.py
  backend/core/log_streamer/log_filter.py
  backend/core/log_streamer/logs_streamer.py
  backend/endpoints/api/v1/restapi.py
  backend/endpoints/ws.py
  backend/helpers/__init__.py
  backend/helpers/rest_helpers.py
  setup.py
Labels: enhancement

#140 Version 2.4.1.32
  .pylintrc
  backend/core/log_streamer/__init__.py
  backend/core/log_streamer/log_client.py
  backend/core/log_streamer/log_filter.py
  backend/core/log_streamer/logs_streamer.py
  backend/endpoints/api/v1/restapi.py
  backend/endpoints/ws.py
  backend/helpers/__init__.py
  backend/helpers/rest_helpers.py
  setup.py
Labels: enhancement

#141 BP-1045 - migrate message server dispatchers to zmqserver
  backend/__init__.py
  backend/core/log_streamer/log_client.py
  backend/core/log_streamer/logs_streamer.py
  backend/endpoints/api/v1/restapi.py
  backend/endpoints/ws.py
  backend/helpers/rest_helpers.py
  setup.py
Labels: bug, enhancement

#143 Version 2.4.1.34
  backend/__init__.py
  backend/core/log_streamer/log_client.py
  backend/core/log_streamer/logs_streamer.py
  backend/endpoints/api/v1/restapi.py
  backend/endpoints/ws.py
  backend/helpers/rest_helpers.py
  setup.py
Labels: bug, enhancement

#147 Version
  README.md
  setup.py
Labels: bug

#148 DP-1073: Update base docker pipeline version
  .github/workflows/DeployOnGitRelease.yml
  .github/workflows/DeployOnMergeMain.yml
  .github/workflows/TestOnPR.yml
  docker/noetic/Dockerfile
Labels: dependencies
